commands/CommitCommand.php
commands/InstallCommand.php
commands/PullCommand.php
commands/PushCommand.php
commands/ReplicateCommand.php
commands/StatusCommand.php
commands/UpdateCommand.php
yii-dev

Hope I didn't miss any direct using.

Use console colors as constants

---

.gitignore

Copied from https://github.com/yiisoft/template

Better `.gitignore` file

---

.travis.yml
commands/CommitCommand.php
commands/InstallCommand.php
commands/PullCommand.php
commands/PushCommand.php
commands/ReplicateCommand.php
commands/StatusCommand.php
commands/UpdateCommand.php
components/console/Color.php
components/console/Executor.php
components/console/Printer.php
components/helpers/FileHelper.php
components/package/Package.php
components/package/PackageList.php
components/package/PackageManager.php
components/package/ReplicationSource.php
yii-dev

Everything is divided into components for the flexibility of further development.
Resolves #11.
Closes #19.
Closes #20.

Componentization of yii-dev script

---

components/console/Printer.php
components/package/PackageManager.php

Explicit notifications about cloning issues

---

commands/LintCommand.php
components/console/Printer.php
components/package/PackageManager.php
composer.json
yii-dev

It can check one or all packages for compliance with PSR2 standard. There is [CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) under the hood.

Lint command

---

README.md
composer.json

See https://github.com/yiisoft/yii-dev-tool/issues/1#issuecomment-507984944

Package renaming

---

components/package/PackageManager.php

See https://github.com/yiisoft/yii-dev-tool/pull/23#issuecomment-541572887

Switching to PSR12

---

components/console/Args.php
yii-dev

Creates new component src/components/Args.php and modified yii-dev.php to uses it.  Closes #28

Split out Command line processing

---

src/Command/StatusCommand.php

This is tested working code and **it can be merged**.
The rest of the commands I'll finalize a bit later.
Related issues: #34, #35

Optimized output of `status` command in normal mode

---

composer.json
src/Command/CommitCommand.php
src/Command/InstallCommand.php
src/Command/LintCommand.php
src/Command/PullCommand.php
src/Command/PushCommand.php
src/Command/ReplicateCommand.php
src/Command/StatusCommand.php
src/Component/Console/PackageCommand.php
src/Component/Console/YiiDevToolStyle.php
src/Component/Package/Package.php
src/Component/Package/PackageList.php

Also:
* installed [cpliakas/git-wrapper](https://github.com/cpliakas/git-wrapper) for git operations
* centralized check of installed yiisoft packages
* tag `<cmd>` has been added to `YiiDevToolStyle` for marking console commands
* some other minor changes (naming, typos, etc.)

Close #31: Automatically configure and use git remote upstream for repository forks

---

src/Command/InstallCommand.php

See https://github.com/yiisoft/yii-dev-tool/issues/42#issuecomment-556997426 for details.

Issue #42: Temporarily ignore git errors during set git upstream

---

README.md
src/Command/ExecCommand.php
src/Component/Console/YiiDevToolApplication.php

Resolves #53: Add exec command

---

src/Command/ExecCommand.php
src/Command/Git/CheckoutBranchCommand.php
src/Command/Git/CommitCommand.php
src/Command/Git/PullCommand.php
src/Command/Git/PushCommand.php
src/Command/Git/StatusCommand.php
src/Command/InstallCommand.php
src/Command/LintCommand.php
src/Command/Replicate/ReplicateComposerConfigCommand.php
src/Command/Replicate/ReplicateFilesCommand.php
src/Component/Console/OutputManager.php
src/Component/Console/PackageCommand.php
src/Component/Console/YiiDevToolApplication.php

Reduce default output verbosity

---

docker-compose.yml

I tried lunch docker but it wasn't work because there is not exists image: yiisoftware/yii-php:7.3-apache.

updated version docker-image on docker-compose.yml

---

src/Command/InstallCommand.php

Because [package](https://github.com/cpliakas/git-wrapper/pull/191) is fixed, this hack can be removed.
Please, [check](https://github.com/yiisoft/yii-dev-tool/issues/42#issue-526258135) it before merge

Remove hack

---

docker-compose.yml
docker/Dockerfile
src/Command/ExecCommand.php
src/Command/Git/CheckoutBranchCommand.php
src/Command/Git/CommitCommand.php
src/Command/Git/PullCommand.php
src/Command/Git/PushCommand.php
src/Command/Git/StatusCommand.php
src/Command/InstallCommand.php
src/Command/LintCommand.php
src/Command/Replicate/ReplicateComposerConfigCommand.php
src/Command/Replicate/ReplicateFilesCommand.php
src/Command/Travis/TravisEnsureCronjobCommand.php
src/Command/Travis/TravisUpdateSlackConfigCommand.php
src/Command/UpdateCommand.php
src/Component/Console/OutputManager.php
src/Component/Console/PackageCommand.php
src/Component/Console/YiiDevToolApplication.php
src/Component/Console/YiiDevToolStyle.php
src/Component/Package/Package.php
src/Component/Package/PackageList.php
src/Component/Package/ReplicationSource.php
src/Component/Travis/API/TravisClient.php
src/Component/Travis/TravisConfig.php
src/Component/Travis/TravisEncryptor.php

Add sqlite3 for full support of yii-demo

---

packages.php

Add user repository to packages

---

composer.json
src/Command/Release/MakeCommand.php
src/Component/Changelog.php
src/Component/Console/YiiDevToolApplication.php

Add draft release command

---

src/Command/Git/RequestPullCommand.php
src/Component/Console/YiiDevToolApplication.php

Implemented gh pr create command

---

src/Component/Package/Package.php

Collapse path resolving

---

src/Command/TestCommand.php
src/Component/Console/YiiDevToolApplication.php

Implemented test command

---

config/replicate/composer.json

Add composer test command

---

src/Command/Replicate/ReplicateComposerConfigCommand.php

Add package context when error triggered

---

src/Command/TestCommand.php

Allow to skip failed test

---

src/Command/TestCommand.php

For now it's available only for `./vendor/bin/phpunit` run.

Ability to filter tests

---

src/Component/Composer/Config/ComposerConfigMerger.php

Add sorting while merging configs

---

config/replicate/files.php

Ignore frontend packages for backend-only packages sets

---

composer.json
config/.gitignore
config/settings.php
src/Command/Github/SettingsCommand.php
src/Component/Console/YiiDevToolApplication.php
src/Component/Package/Package.php

Add settings command

---

src/App/Command/Composer/ComposerFixDependenciesCommand.php
src/Infrastructure/Composer/ComposerPackage.php
src/Infrastructure/Composer/ComposerPackageUsageAnalyzer.php
src/Infrastructure/Composer/Config/ComposerConfig.php

Improve composer/fix-dependencies command

---

src/App/Command/Release/MakeCommand.php
src/Infrastructure/Composer/Config/ComposerConfig.php
src/Infrastructure/Composer/Config/Dependency/ComposerConfigDependency.php

Add stability check before release

---

src/App/Command/InstallCommand.php

Relative symlinks for containerized environment

---

src/App/Command/Git/CheckoutCommand.php
src/App/YiiDevToolApplication.php

Rename command git/checkout-branch -> git/checkout

---

docker/Dockerfile

Fix install of sqlite3

---

composer.json

Update yiisoft/arrays dependency

---

src/App/Command/InstallCommand.php

Don't install package in update mode.

---

README.md
src/App/Command/ListPackagesCommand.php
src/App/YiiDevToolApplication.php

| Is bugfix?    | No
| New feature?  | Yes
| Breaks BC?    | No

Command to list all enabled packages

---

src/App/Command/InstallCommand.php

Add git pull before composer update

---

src/App/Component/Package/PackageList.php

Create symbolic links only for enabled packages

---

src/App/Component/Console/PackageCommand.php

| Fixed issues  | 
It sorts packages for processing alphabetically

Sort packages before processing

---

packages.php

Add missed package

---

composer.json
src/App/Command/InstallCommand.php

Fix unlink in Windows

---

src/Infrastructure/Changelog.php

Fix sort lines in changelog on `release/make`

---

README.md
src/App/Command/Composer/UpdateCommand.php
src/App/Command/ExecCommand.php
src/App/Command/Git/CheckoutCommand.php
src/App/Command/Git/CommitCommand.php
src/App/Command/Git/PullCommand.php
src/App/Command/Git/PushCommand.php
src/App/Command/Git/RequestPullCommand.php
src/App/Command/Git/StatusCommand.php
src/App/Command/InstallCommand.php
src/App/Command/ListCommand.php
src/App/Command/TestCommand.php
src/App/Command/UpdateCommand.php
src/App/Component/Console/PackageCommand.php
src/App/PackageService.php
src/App/YiiDevToolApplication.php

| Fixed issues  | #170, #151, partly #143

Run `git pull` on `update` command + Add `composer/update` + Add command aliases 

---

packages.php

Add runner packages

---

src/Infrastructure/Changelog.php

Before:
```
- no changes in this release.
- Bug: Fix incorrect method in `web` configuration (vjik)
```
After:
```
- no changes in this release.
- Bug: Fix incorrect method in `web` configuration (vjik)
```

Remove unnecessary empty line in changelog

---

README.md
src/App/Command/Git/CloneCommand.php
src/App/Command/InstallCommand.php
src/App/Component/Console/PackageCommand.php
src/App/PackageService.php
src/App/YiiDevToolApplication.php

Add git/clone command

---

src/App/Component/Package/PackageErrorList.php

Adopt to PHP8.1

---

packages.php

Add `rbac-rules-container` to packages

---

.github/workflows/build.yml
composer.json
packages.php

| Fixed issues  | 
✅ Added new package.
✅ Fixed minimal PHP version.

Add package

---

README.md
src/App/Command/Release/MakeCommand.php
src/Infrastructure/Changelog.php

Release on GitHub

---

src/App/Command/Release/MakeCommand.php
src/Infrastructure/Changelog.php

Adjust title, notes format

---

.github/workflows/build.yml

Use reusables actions.

---

packages.php

| Fixed issues  | add new package

Add `validator-rules-container` package

---

src/App/Command/Composer/ComposerFixDependenciesCommand.php
src/App/Command/Composer/UpdateCommand.php
src/App/Command/ExecCommand.php
src/App/Command/Git/CheckoutCommand.php
src/App/Command/Git/CloneCommand.php
src/App/Command/Git/CommitCommand.php
src/App/Command/Git/PullCommand.php
src/App/Command/Git/PushCommand.php
src/App/Command/Git/RequestPullCommand.php
src/App/Command/Git/StatusCommand.php
src/App/Command/InstallCommand.php
src/App/Command/LintCommand.php
src/App/Command/ListCommand.php
src/App/Command/Release/MakeCommand.php
src/App/Command/Release/WhatCommand.php
src/App/Command/Replicate/ReplicateFilesCommand.php
src/App/Command/Stats/ContributorsCommand.php
src/App/Command/TestCommand.php
src/App/Command/UpdateCommand.php
src/App/Component/Console/PackageCommand.php
src/App/PackageService.php
src/App/YiiDevToolApplication.php
src/Infrastructure/CodeUsage/NamespaceUsageFinder.php
src/Infrastructure/Composer/ComposerInstallation.php
src/Infrastructure/Composer/ComposerPackage.php
src/Infrastructure/Composer/Config/ComposerConfigDependenciesModifier.php

| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.

Separate chain calls

---

composer.json
src/App/Command/Git/PushCommand.php
src/App/Command/Release/MakeCommand.php
src/App/Component/Package/Package.php

Replace cpliakas/git-wrapper to symplify/git-wrapper

---

src/App/Command/Release/MakeCommand.php

Fix `release/make` command

---

src/Infrastructure/Changelog.php

Now in master sort of changelog work if version of release equal to version in changelog only.

Fix changelog sort

---

README.md
src/App/Command/DisableCommand.php
src/App/Command/EnableCommand.php
src/App/YiiDevToolApplication.php

Add `enable` and `disable` commands

---

src/App/Command/Composer/UpdateCommand.php
src/App/Command/UpdateCommand.php

Add --ignore-platform-reqs option

---

src/App/Command/Github/ProtectBranchCommand.php
src/App/Command/Github/SettingsCommand.php
src/App/Command/Release/MakeCommand.php

Enhance error message

---

composer.json
src/App/Command/DisableCommand.php
src/App/Command/EnableCommand.php

Already enabled/disabled packages are taken into account separately:

Improve `enable` and `disable` commands + Update `yiisoft/files` dependency

---

README.md
src/App/Command/Github/ForksRepositoriesCommand.php
src/App/YiiDevToolApplication.php

Add command to create forks of github repositories

---

README.md
owner-packages.php
src/App/Command/Release/WhatCommand.php
src/App/Command/Stats/ContributorsCommand.php
src/App/Component/Console/PackageCommand.php
src/App/Component/Package/Package.php
src/App/Component/Package/PackageList.php

Add the ability to specify the package owner

---

src/App/Command/Release/WhatCommand.php

Remove duplicate packages in command release/what

---

README.md
src/App/Command/Github/SyncUpstreamRepositoriesCommand.php
src/App/YiiDevToolApplication.php

Add command for sync forks repositories

---

packages.php

Add `actions` package

---

src/App/Command/Git/CloneCommand.php
src/App/Command/InstallCommand.php
src/App/Component/Console/PackageCommand.php

Check ssh connection

---

src/App/Command/Github/SyncUpstreamRepositoriesCommand.php

Fix sync command

---

config/replicate/files.php

Add composer require checker replication config

---

src/App/Command/Composer/UpdateCommand.php
src/App/Command/InstallCommand.php
src/App/Command/UpdateCommand.php
src/App/PackageService.php

Reverts yiisoft/yii-dev-tool#230
https://github.com/yiisoft/yii-dev-tool/issues/166
https://github.com/yiisoft/yii-dev-tool/issues/142

Revert "Create symbol links only target packages "

---

README.md
src/App/Command/AddChangelogCommand.php
src/App/Command/Release/MakeCommand.php
src/App/YiiDevToolApplication.php
src/Infrastructure/Changelog.php

Add changelog command

---

README.md
src/App/Command/EnableCommand.php
src/App/Command/SwitchCommand.php
src/App/YiiDevToolApplication.php

Add `switch` command that enable specified packages and disable others

---

src/App/PackageService.php

Fix package path

---

src/App/Command/Release/MissingCommand.php
src/App/YiiDevToolApplication.php
src/Infrastructure/Changelog.php

Add `release/missing` command

---

packages.php

Add `yii-twig` package

---

src/App/Command/SwitchCommand.php
src/App/Component/Console/OutputManager.php

Fix switch command output

---

packages.php

Remove `yii-captcha` package

---

.gitignore
Makefile
README.md
docker-compose.override.dist.yml
docker-compose.yml
docker/Dockerfile
docker/README.md
docker/bash
docker/home/.bashrc
docker/home/.gitignore
docker/home/.profile

| Breaks BC?    | probably yes but docker stack was not really working before

Improve Docker Stack

---

composer.json
src/Infrastructure/Changelog.php

Fix #259: Fix release/make

---

composer.json

Fixes CI build erros, eg. https://github.com/yiisoft/yii-docker/actions/runs/4143167497/jobs/7164696166#step:9:186

allow plugin php-http/discovery in composer.json

---

src/App/Command/Composer/UpdateCommand.php
src/App/Command/InstallCommand.php
src/App/Command/UpdateCommand.php
src/App/Component/Console/PackageCommand.php

Add option --no-symlinks

---

packages.php

Update packages list

---

README.md
src/App/Command/IdeCommand.php
src/App/Component/PhpStorm/Folders.php
src/App/YiiDevToolApplication.php

Fix #266: Implement ide command to automatically configure PhpStorm

---

README.md
src/App/Command/Release/MakeCommand.php
src/App/Component/Console/PackageCommand.php
src/App/Component/Package/ReplicationSet.php
src/Infrastructure/CodeUsage/NamespaceUsageFinder.php
src/Infrastructure/Composer/Config/ComposerConfig.php
tests/Infrastructure/Composer/Config/ComposerConfigMergerTest.php

Fix typo in README

---

Makefile
docker-compose.override.dist.yml
docker/Dockerfile
docker/README.md

Enable xDebug in the Docker environment

---

packages.php
src/Infrastructure/Changelog.php

Add packages "hydrator", "input-validation" and "input-http"

---

packages.php

Actualize "input-validation" package name

---

packages.php

Add package "proxy-middleware"

---

packages.php

Remove `yiisoft/request-model`

---

packages.php

Add `yiisoft/form-model` package

---

src/Infrastructure/Changelog.php

Fix missing lines with equal keys in changelog

---

packages.php
src/App/Component/Console/YiiDevToolStyle.php

Add `yiisoft/file-router` package

---

packages.php

Add `request-provider` package

---

packages.php

Add `data-cycle` package

---

packages.php

Rename `yii-view` to `yii-view-renderer`

---

packages.php

Add `yiisoft/mailer-view` package

---

src/App/Command/Composer/UpdateCommand.php
src/App/Command/DisableCommand.php
src/App/Command/EnableCommand.php
src/App/Command/ExecCommand.php
src/App/Command/Git/CheckoutCommand.php
src/App/Command/Git/CloneCommand.php
src/App/Command/Git/CommitCommand.php
src/App/Command/Git/PullCommand.php
src/App/Command/Git/PushCommand.php
src/App/Command/Git/RequestPullCommand.php
src/App/Command/Git/StatusCommand.php
src/App/Command/Github/SyncUpstreamRepositoriesCommand.php
src/App/Command/IdeCommand.php
src/App/Command/InstallCommand.php
src/App/Command/ListCommand.php
src/App/Command/Release/MissingCommand.php
src/App/Command/SwitchCommand.php
src/App/Command/TestCommand.php
src/App/Command/UpdateCommand.php

Use attributes for symfony console commands

---

src/App/Command/Git/CloneCommand.php
src/App/Command/InstallCommand.php

Fix passing command name to `PackageService`

---

packages.php

Add `psr-emitter` package

---

.github/workflows/rector.yml
composer.json
rector.php

Fix rector

---

config/replicate/files.php

Remove scrutinizer

---

README.md
config/.gitignore
config/config.local.php.example
dev/.gitignore
src/App/Component/Console/PackageCommand.php
src/App/YiiDevToolApplication.php
yii-dev

Allow adjusting dev directory location

---

src/App/Command/Release/MakeCommand.php
src/Infrastructure/Composer/Config/ComposerConfig.php

Generate release news text

---

src/App/Command/Release/MakeCommand.php

Fix link in release news text
